language: ruby
sudo: required
rvm:
  - 2.2
# whitelist
branches:
  only:
    - gh-pages
before_install:
  - gem install html-proofer
script:
  - bundle exec jekyll build
  - bundle exec htmlproof ./_site --check-favicon --check-html
